Repository classic-terra/core, pull requests merged in 2023-03, with the labels that each got.

#170 fixing compiler warnings and errors
  app/app.go
  app/keepers/keepers.go
  app/keepers/keys.go
  cmd/terrad/config.go
  cmd/terrad/root.go
  custom/auth/ante/tax.go
  custom/auth/client/utils/feeutils.go
  custom/bank/wasm/interface.go
  custom/bank/wasm/interface_test.go
  custom/distribution/wasm/interface.go
  custom/distribution/wasm/interface_test.go
  custom/gov/wasm/interface.go
  custom/gov/wasm/interface_test.go
  custom/staking/wasm/interface.go
  custom/staking/wasm/interface_test.go
  x/market/wasm/interface.go
  x/market/wasm/interface_test.go
  x/oracle/wasm/interface.go
  x/oracle/wasm/interface_test.go
  x/treasury/wasm/interface.go
  x/treasury/wasm/interface_test.go
Labels: enhancement

#138 Min Initial Deposit (Recreated using main as base branch)
  app/app.go
  app/upgrades/v3/constants.go
  app/upgrades/v3/upgrades.go
  custom/auth/ante/ante.go
  custom/auth/ante/expected_keeper.go
  custom/auth/ante/min_initial_deposit.go
  custom/auth/ante/min_initial_deposit_test.go
  proto/terra/treasury/v1beta1/treasury.proto
  x/treasury/keeper/migrations.go
  x/treasury/keeper/params.go
  x/treasury/legacy/v05/migrate_test.go
  x/treasury/module.go
  x/treasury/types/params.go
  x/treasury/types/treasury.pb.go
  x/wasm/types/expected_keeper.go
Labels: enhancement, in scope

#177 V3 Upgrade Handling
  app/app.go
  app/upgrades/types.go
  app/upgrades/v2/constants.go
  app/upgrades/v2/upgrades.go
  app/upgrades/v3/constants.go
  app/upgrades/v3/upgrades.go
Labels: enhancement, in scope

#176 V0.45.13 proposal
  app/modules.go
  go.mod
  go.sum
  x/wasm/keeper/recursive_test.go
  x/wasm/keeper/submsg_test.go
Labels: enhancement, in scope

#172 Terra operator docker refactor
  Dockerfile.terraclassic.terrad-binary
  Makefile
  README.md
  contrib/terra-operator/Dockerfile
  contrib/terra-operator/Dockerfile.core
  contrib/terra-operator/README.md
  contrib/terra-operator/build_all.sh
  contrib/terra-operator/create-validator.sh
  contrib/terra-operator/docker-compose.build.yml
  contrib/terra-operator/docker-compose.node.yml
  contrib/terra-operator/entrypoint.sh
  contrib/terra-operator/keys-add.sh
  contrib/terra-operator/keys.json
  contrib/terra-operator/test-node-setup.sh
  docker-compose.build.yml
  docker/Dockerfile
  docker/entrypoint.sh
Labels: enhancement, out of scope

#185 add script for min initial deposit ratio test
  Makefile
  contrib/localnet/deposit-test.sh
Labels: enhancement, Value-Add

#187 fix issues with liveness test
  .github/workflows/test.yml
  cmd/terrad/testnet.go
Labels: bug
