Repository classic-terra/core, pull requests merged in 2023-01, with the labels that each got.

#7 Fix Github Action not running
  .github/workflows/docker.yml
  .github/workflows/lint.yml
  .github/workflows/proto.yml
  Dockerfile.terraclassic.terrad-binary
  Makefile
  contrib/images/Makefile
  docker-compose.yml
  docker-compose/docker-compose.yml
  docker/README.md
  docker/build_all.sh
Labels: enhancement, in_scope

#4 - "Burntax split" in antehandler for Eds prop
  custom/auth/ante/ante.go
  custom/auth/ante/ante_test.go
  custom/auth/ante/burntax.go
  custom/auth/ante/burntax_test.go
Labels: enhancement

#21 Added command in makefile to purge wasm from genesis json
  Makefile
Labels: enhancement, in_scope

#25 Disable ARM64 target to allow alpine build to pass
  .github/workflows/docker.yml
Labels: bug

#27 Tax rate
  custom/auth/ante/burntax.go
  custom/auth/ante/expected_keeper.go
  proto/terra/buf.gen.gogo.yaml
  proto/terra/buf.lock
  proto/terra/buf.yaml
  proto/terra/treasury/v1beta1/treasury.proto
  x/treasury/keeper/keeper.go
  x/treasury/keeper/migrations.go
  x/treasury/legacy/v05/migrate.go
  x/treasury/legacy/v05/migrate_test.go
  x/treasury/module.go
  x/treasury/types/params.go
  x/treasury/types/treasury.pb.go
  x/wasm/types/expected_keeper.go
Labels: enhancement, in scope

#40 allow uluna to be taxed
  custom/auth/client/utils/feeutils.go
Labels: bug, in scope

#48 Fix makefile for linux builds
  Makefile
Labels: enhancement

#44 move version map register to begin block
  .gitignore
  app/app.go
  types/alias.go
  types/fork/height.go
Labels: enhancement, in scope

#54 add whitelist test
  custom/auth/ante/burntax_test.go
Labels: enhancement, out of scope

#47 Whitelist concept
  custom/auth/ante/burntax.go
  custom/auth/ante/burntax_test.go
Labels: enhancement, out of scope

#68 Feat/ibc whitelist
  app/app.go
  custom/auth/ante/tax.go
  types/alias.go
  types/fork/height.go
Labels: enhancement, in scope

#67 Wasm upgrade from main
  Dockerfile
  custom/auth/ante/burntax_test.go
  go.mod
  go.sum
  x/wasm/genesis_test.go
  x/wasm/handler_test.go
  x/wasm/keeper/api.go
  x/wasm/keeper/bench_test.go
  x/wasm/keeper/connector.go
  x/wasm/keeper/contract.go
  x/wasm/keeper/contract_test.go
  x/wasm/keeper/custom_test.go
  x/wasm/keeper/ioutil_test.go
  x/wasm/keeper/keeper.go
  x/wasm/keeper/keeper_test.go
  x/wasm/keeper/legacy_querier_test.go
  x/wasm/keeper/msg_server_test.go
  x/wasm/keeper/querier_test.go
  x/wasm/keeper/recursive_test.go
  x/wasm/keeper/reflect_test.go
  x/wasm/keeper/staking_test.go
  x/wasm/keeper/submsg_test.go
  x/wasm/keeper/test_utils.go
  x/wasm/keeper/testdata/bindings_tester.wasm
  x/wasm/keeper/testdata/burner.wasm
  x/wasm/keeper/testdata/hackatom.wasm
  x/wasm/keeper/testdata/hackatom.wasm.gzip
  x/wasm/keeper/testdata/maker.wasm
  x/wasm/keeper/testdata/reflect.wasm
  x/wasm/keeper/testdata/staking.wasm
  x/wasm/keeper/testdata/test_contract.wasm
  x/wasm/keeper/wasm_interface_test.go
  x/wasm/simulation/test_contract.go
  x/wasm/types/connector.go
  x/wasm/types/errors.go
  x/wasm/types/gas_meter.go
  x/wasm/types/gas_meter_test.go
  x/wasm/types/wasmer_engine.go
Labels: enhancement, in scope

#51 Constrained pool to ensure LUNC can never have more then 2T supply
  x/market/keeper/swap.go
  x/market/keeper/swap_test.go
  x/market/types/errors.go
Labels: enhancement, out of scope
