Repository classic-terra/core, pull requests merged in 2023-06, with the labels that each got.

#276 fix: wasm DispatchMsg should return events and data
  custom/wasm/keeper/handler_plugin.go
Labels: bug, state machine breaking

#287 chore: prepare v2.1.2 release
  CHANGELOG.md
Labels: documentation

#294 tools: add mergify
  .mergify.yml
Labels: github_actions
