Repository classic-terra/core, pull requests merged in 2023-02, with the labels that each got.

#93 Upgrade to golang 1.18 and fix ad-hoc security vulnerabilities
  .github/workflows/docker.yml
  .github/workflows/test.yml
  Dockerfile
  go.mod
  go.sum
  shared.Dockerfile
Labels: enhancement, out of scope, security

#91 Main branch: gh update test
  .github/workflows/test.yml
  Dockerfile
  Makefile
  README.md
  contrib/images/Makefile
  contrib/images/terrad-env/Dockerfile
  contrib/images/terrad-env/cosmovisor-wrapper.sh
  contrib/updates/Dockerfile.cosmovisor
  contrib/updates/Makefile
  contrib/updates/docker-compose.yml
  contrib/updates/prepare_cosmovisor.sh
  contrib/updates/upgrade-test.sh
Labels: enhancement, out of scope

#98 Update CHANGELOG and README
  CHANGELOG.md
  README.md
Labels: documentation

#106 fix ungraceful error on failed client tax query
  custom/auth/client/utils/feeutils.go
Labels: bug

#105 Updated docker assets
  Dockerfile.terraclassic.terrad-binary
  Makefile
  README.md
  docker-compose.build.yml
  docker-compose.node.yml
  docker-compose.yml
  docker/Dockerfile
  docker/create-validator.sh
  docker/entrypoint.sh
  docker/keys-add.sh
Labels: enhancement, out of scope

#103 v1.x backport: add burn tax split logic
  app/app.go
  app/upgrades/v2/constants.go
  app/upgrades/v2/upgrades.go
  custom/auth/ante/ante.go
  custom/auth/ante/ante_test.go
  custom/auth/ante/burntax.go
  custom/auth/ante/burntax_test.go
  custom/auth/ante/expected_keeper.go
  docs/core/proto-docs.md
  proto/terra/treasury/v1beta1/treasury.proto
  scripts/run-node.sh
  scripts/upgrade-test.sh
  x/treasury/keeper/keeper.go
  x/treasury/keeper/migrations.go
  x/treasury/legacy/v05/migrate.go
  x/treasury/legacy/v05/migrate_test.go
  x/treasury/module.go
  x/treasury/types/params.go
  x/treasury/types/treasury.pb.go
  x/wasm/types/expected_keeper.go
Labels: enhancement, in scope

#113 fix: burn tax split bug
  custom/auth/ante/ante.go
  custom/auth/ante/burntax.go
  custom/auth/ante/burntax_test.go
  custom/auth/ante/expected_keeper.go
Labels: bug, in scope

#119 chore: add missing changelogs
  CHANGELOG.md
Labels: documentation, out of scope

#118 build: localnet for Apple Silicon
  .github/workflows/test.yml
  CHANGELOG.md
  Makefile
  app/sim_test.go
  contrib/images/Makefile
  contrib/localnet/Makefile
  contrib/localnet/localnet_liveness.sh
  contrib/localnet/terrad-env/Dockerfile
  contrib/localnet/terrad-env/entrypoint.sh
  docker-compose.yml
  sims.mk
Labels: out of scope, Value-Add

#101 fix: add github action for upgrade testing
  .github/workflows/test.yml
  CHANGELOG.md
  Dockerfile
  Makefile
  app/app.go
  contrib/localnet/Makefile
  contrib/localnet/terrad-env/Dockerfile
  contrib/localnet/terrad-env/cosmovisor-entrypoint.sh
  contrib/updates/Dockerfile.cosmovisor
  contrib/updates/Makefile
  contrib/updates/docker-compose.yml
  contrib/updates/prepare_cosmovisor.sh
  contrib/updates/upgrade-test.sh
  scripts/upgrade-test.sh
Labels: enhancement, out of scope

#124 add acceptance criteria section to feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation

#128 feat: panic at columbus genesis
  CHANGELOG.md
  app/app.go
Labels: enhancement, Value-Add

#108 feat: update wasmvm to 0.16.7
  Dockerfile
  go.mod
  go.sum
  x/wasm/genesis_test.go
  x/wasm/handler_test.go
  x/wasm/keeper/bench_test.go
  x/wasm/keeper/contract.go
  x/wasm/keeper/contract_test.go
  x/wasm/keeper/custom_test.go
  x/wasm/keeper/ioutil_test.go
  x/wasm/keeper/keeper.go
  x/wasm/keeper/keeper_test.go
  x/wasm/keeper/legacy_querier_test.go
  x/wasm/keeper/msg_server_test.go
  x/wasm/keeper/querier_test.go
  x/wasm/keeper/recursive_test.go
  x/wasm/keeper/reflect_test.go
  x/wasm/keeper/staking_test.go
  x/wasm/keeper/submsg_test.go
  x/wasm/keeper/test_utils.go
  x/wasm/keeper/wasm_interface_test.go
  x/wasm/types/errors.go
  x/wasm/types/wasmer_engine.go
Labels: enhancement, out of scope, Value-Add

#121 refactor: add number of validators and chain id as testnet parameters
  Makefile
  docker-compose.yml
Labels: enhancement, out of scope

#107 feat: add burn tax exemption list
  .gitignore
  app/app.go
  app/upgrades/v2/upgrades.go
  custom/auth/ante/burntax.go
  custom/auth/ante/burntax_test.go
  custom/auth/ante/expected_keeper.go
  docs/core/proto-docs.md
  proto/terra/treasury/v1beta1/gov.proto
  proto/terra/treasury/v1beta1/query.proto
  scripts/burn-tax-exemption-test.sh
  x/treasury/client/cli/gov_tx.go
  x/treasury/client/cli/query.go
  x/treasury/client/proposal_handler.go
  x/treasury/client/rest/query.go
  x/treasury/keeper/gov.go
  x/treasury/keeper/keeper.go
  x/treasury/keeper/keeper_test.go
  x/treasury/keeper/legacy_querier.go
  x/treasury/keeper/legacy_querier_test.go
  x/treasury/keeper/migrations.go
  x/treasury/keeper/params.go
  x/treasury/keeper/querier.go
  x/treasury/keeper/test_utils.go
  x/treasury/module.go
  x/treasury/proposal_handler.go
  x/treasury/types/codec.go
  x/treasury/types/errors.go
  x/treasury/types/gov.go
  x/treasury/types/gov.pb.go
  x/treasury/types/keys.go
  x/treasury/types/querier.go
  x/treasury/types/query.pb.go
  x/treasury/types/query.pb.gw.go
  x/wasm/types/expected_keeper.go
Labels: enhancement, in scope

#129 ci: add codeql ci
  .github/workflows/codeql.yml
  app/encoding.go
Labels: github_actions, out of scope

#135 Add app.DistrKeeper to HandlerOptions during AnteHandler instantiation
  app/app.go
Labels: bug

#142 docs: add testing framework document
  tests/README.md
Labels: documentation, enhancement, github_actions
